conver install sys deps form bash to sh script

diff --git a/.github/workflows/e2e-test-linux-distros.yml b/.github/workflows/e2e-test-linux-distros.yml
--- a/.github/workflows/e2e-test-linux-distros.yml
+++ b/.github/workflows/e2e-test-linux-distros.yml
@@ -35,32 +35,30 @@ jobs:
         with:
           node-version: ${{ matrix.node-version }}
 
-      - name: 🧱 Install Dependencies
+      - name: 🧱 Install system dependencies
         run: |
-          # apt-get install --no-install-recommends -y nodejs npm rpm libarchive-tools
-          packagesNeeded=(nodejs npm)
-          if [ -x "$(command -v apk)" ];
-          then
-              apk add --no-cache "${packagesNeeded[@]}"
-          elif [ -x "$(command -v apt-get)" ];
-          then
-              apt-get install --no-install-recommends -y "${packagesNeeded[@]}" rpm libarchive-tools
-          elif [ -x "$(command -v dnf)" ];
-          then
-              dnf install -y "${packagesNeeded[@]}"
-          elif [ -x "$(command -v pacman)" ];
-          then
-              pacman -S "${packagesNeeded[@]}" --noconfirm
-          elif [ -x "$(command -v zypper)" ];
-          then
-              zypper install -y "${packagesNeeded[@]}"
+          # Define the packages needed
+          packagesNeeded="nodejs npm"
+
+          # Determine the package manager and install required packages
+          if command -v apk > /dev/null 2>&1; then
+              apk add --no-cache $packagesNeeded
+          elif command -v apt-get > /dev/null 2>&1; then
+              apt-get update
+              apt-get install --no-install-recommends -y $packagesNeeded rpm libarchive-tools
+          elif command -v dnf > /dev/null 2>&1; then
+              dnf install -y $packagesNeeded
+          elif command -v pacman > /dev/null 2>&1; then
+              pacman -S --noconfirm $packagesNeeded
+          elif command -v zypper > /dev/null 2>&1; then
+              zypper install -y $packagesNeeded
           else
-              echo "FAILED TO INSTALL PACKAGE: Package manager not found. You must manually install: "${packagesNeeded[@]}"">&2;
+              echo "FAILED TO INSTALL PACKAGES: Package manager not found. You must manually install: $packagesNeeded" >&2
+              exit 1
           fi
 
-          npm ci
-
-
+      - name: Install npm dependencies
+        run: npm ci
 
       - name: 📦 Bundle Application
         env:
